sa_sr_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ShoulderJRotate
  pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.0
    p: 60.0

sa_ss_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ShoulderJSwing
  pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.0
    p: 60.0

sa_es_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ElbowJSwing
  pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.0
    p: 60.0

sa_er_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ElbowJRotate
  pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.0
    p: 60.0

r_arm_cartesian_pose_controller:
  type: robot_mechanism_controllers/CartesianPoseController
  root_name: shadowarm_base
  tip_name: palm
  fb_trans:
    p: 20.0
    i: 0.5
    d: 0.0
    i_clamp: 1.0
  fb_rot:
    p: 0.5
    i: 0.1
    d: 0.0
    i_clamp: 0.2

r_arm_joint_trajectory_controller:
  type: robot_mechanism_controllers/JointSplineTrajectoryController
  joints:
    - ShoulderJRotate
    - ShoulderJSwing
    - ElbowJSwing
    - ElbowJRotate
    - WRJ2
    - WRJ1
  gains:
    ShoulderJRotate: {p: 140.0, d: 30.0}
    ShoulderJSwing: {p: 140.0, d: 30.0}
    ElbowJSwing: {p: 140.0, d: 30.0}
    ElbowJRotate: {p: 140.0, d: 30.0}
    WRJ2: {p: 140.0, d: 30.0}
    WRJ1: {p: 140.0, d: 30.0}
